#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require_relative 'lib/xoxo'

# # Setup
# unless File.exist?(config_dir)
#   begin
#     FileUtils.mkdir_p(users_dir)
#     config = {}
#     puts 'Your Gmail account?'
#     config['username'] = gets.chomp
#     puts "Password for #{config['username']}"
#     config['password'] = gets.chomp
#     File.open(config_file_path, 'w') { |f| f << config.to_yaml }
#     puts 'The email address of your sweet beloved?'
#     recipient = gets.chomp
#     # TODO: Refactor candies dir path
#     FileUtils.mkdir_p(File.join(users_dir, recipient, 'candies'))
#   rescue
#     FileUtils.rm_rf(config_dir, secure: true)
#     fail
#   end
# end

context = Context.new('~/.xoxo')
GmailSession.init context.config
Xoxo.run!(context)
